### ISSUE TITLE
Errors in agent.log

### ISSUE THREAD

**Issue by blaberdia** [wifinigel/wiperf#10] opened 2020-03-10 14:46 UTC
Seeing the following errors when running a wlanpi in wiperf mode:

2020-03-10 10:40:05,419 - Probe_Log - INFO - *****************************************************
2020-03-10 10:40:05,420 - Probe_Log - INFO -  Starting logging...
2020-03-10 10:40:05,421 - Probe_Log - INFO - *****************************************************
2020-03-10 10:40:05,442 - Probe_Log - INFO - No lock file found. Creating lock file.
2020-03-10 10:40:05,443 - Probe_Log - INFO - ########## wireless connection checks ##########
2020-03-10 10:40:05,444 - Probe_Log - INFO - Checking wireless connection available.
2020-03-10 10:40:05,516 - Probe_Log - INFO - Checking we're connected to the network
2020-03-10 10:40:05,518 - Probe_Log - INFO - Checking we have an IP address.
2020-03-10 10:40:05,534 - Probe_Log - INFO - Checking we can do a DNS lookup.
2020-03-10 10:41:01,593 - Probe_Log - ERROR - DNS seems to be failing, bouncing wireless interface. Err msg: [Errno -2] Name or service not known
2020-03-10 10:41:01,596 - Probe_Log - ERROR - Attempting to recover by bouncing wireless interface...
2020-03-10 10:41:01,597 - Probe_Log - ERROR - Bouncing WLAN interface
2020-03-10 10:41:01,599 - Probe_Log - INFO - Bouncing interface wlan0 (platform type = wlanpi)
2020-03-10 10:41:01,643 - Probe_Log - ERROR - if bounce command appears to have failed. Error: sudo: no tty present and no askpass program specified

2020-03-10 10:41:01,645 - Probe_Log - ERROR - Returning error...
2020-03-10 10:41:01,646 - Probe_Log - ERROR - Bounce completed. Exiting script.
2020-03-10 10:41:01,648 - Probe_Log - INFO - removing lock file

The first test after going into wiperf mode completes successfully then the 2nd test in the cycle fails with the above log entries. Eventually, watchdog kicks in and reboots the wlanpi and the first test is successful and 2nd fails, etc. This cycle continues indefinitely.

**Comment by wifinigel** [comment] 2020-03-10 16:47
Add the following entries to the /etc/sudoers.d/wlanpidump file:

```
/sbin/ifdown 
/sbin/ifup
```
The modified file content should be as follows:
```
wlanpi ALL = (root) NOPASSWD: /sbin/iwconfig, /usr/sbin/iw, /sbin/dhclient, /sbin/ifconfig, /sbin/reboot, /bin/kill, /bin/date, /sbin/ifdown, /sbin/ifup
```

Thanks for the spot, I will add a note to the wifperf docs. The relevant WLAN Pi repo where this is set has been modified for the next image build too.

**Comment by blaberdia** [comment] 2020-03-10 17:23
Added the requested lines to wlanpidump file and tailed the log for for the next test cycle which gave the following output:

2020-03-10 13:20:05,139 - Probe_Log - INFO - *****************************************************
2020-03-10 13:20:05,140 - Probe_Log - INFO -  Starting logging...
2020-03-10 13:20:05,141 - Probe_Log - INFO - *****************************************************
2020-03-10 13:20:05,162 - Probe_Log - INFO - No lock file found. Creating lock file.
2020-03-10 13:20:05,164 - Probe_Log - INFO - ########## wireless connection checks ##########
2020-03-10 13:20:05,165 - Probe_Log - INFO - Checking wireless connection available.
2020-03-10 13:20:05,240 - Probe_Log - INFO - Checking we're connected to the network
2020-03-10 13:20:05,241 - Probe_Log - INFO - Checking we have an IP address.
2020-03-10 13:20:05,259 - Probe_Log - INFO - Checking we can do a DNS lookup.
2020-03-10 13:21:01,316 - Probe_Log - ERROR - DNS seems to be failing, bouncing wireless interface. Err msg: [Errno -2] Name or service not known
2020-03-10 13:21:01,319 - Probe_Log - ERROR - Attempting to recover by bouncing wireless interface...
2020-03-10 13:21:01,321 - Probe_Log - ERROR - Bouncing WLAN interface
2020-03-10 13:21:01,322 - Probe_Log - INFO - Bouncing interface wlan0 (platform type = wlanpi)
2020-03-10 13:21:47,427 - Probe_Log - ERROR - if bounce command appears to have failed. Error: Killed old client process
Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

/etc/dhcp/dhclient.conf line 21: semicolon expected.
#}
  ^
Listening on LPF/wlan0/20:0d:b0:32:35:f1
Sending on   LPF/wlan0/20:0d:b0:32:35:f1
Sending on   Socket/fallback
DHCPRELEASE on wlan0 to 192.0.2.1 port 67
Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

/etc/dhcp/dhclient.conf line 21: semicolon expected.
#}
  ^
Listening on LPF/wlan0/20:0d:b0:32:35:f1
Sending on   LPF/wlan0/20:0d:b0:32:35:f1
Sending on   Socket/fallback
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 6
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 10
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 14
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 13
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 15
DHCPREQUEST of 198.21.209.7 on wlan0 to 255.255.255.255 port 67
DHCPOFFER of 198.21.209.7 from 192.0.2.1
DHCPACK of 198.21.209.7 from 192.0.2.1
bound to 198.21.209.7 -- renewal in 385 seconds.
RTNETLINK answers: File exists
run-parts: /etc/network/if-up.d/route exited with return code 2
ifup: failed to bring up wlan0

2020-03-10 13:21:47,428 - Probe_Log - ERROR - Returning error...
2020-03-10 13:21:47,430 - Probe_Log - ERROR - Bounce completed. Exiting script.
2020-03-10 13:21:47,431 - Probe_Log - INFO - removing lock file

**Comment by blaberdia** [comment] 2020-03-10 17:37
Also got this error on one of the tests:

2020-03-10 13:35:04,835 - Probe_Log - INFO - *****************************************************
2020-03-10 13:35:04,836 - Probe_Log - INFO -  Starting logging...
2020-03-10 13:35:04,837 - Probe_Log - INFO - *****************************************************
2020-03-10 13:35:04,858 - Probe_Log - INFO - No lock file found. Creating lock file.
2020-03-10 13:35:04,859 - Probe_Log - INFO - ########## wireless connection checks ##########
2020-03-10 13:35:04,860 - Probe_Log - INFO - Checking wireless connection available.
2020-03-10 13:35:04,935 - Probe_Log - INFO - Checking we're connected to the network
2020-03-10 13:35:04,936 - Probe_Log - INFO - Checking we have an IP address.
2020-03-10 13:35:04,954 - Probe_Log - INFO - Checking we can do a DNS lookup.
2020-03-10 13:36:01,017 - Probe_Log - ERROR - DNS seems to be failing, bouncing wireless interface. Err msg: [Errno -2] Name or service not known
2020-03-10 13:36:01,020 - Probe_Log - ERROR - Attempting to recover by bouncing wireless interface...
2020-03-10 13:36:01,022 - Probe_Log - ERROR - Bouncing WLAN interface
2020-03-10 13:36:01,023 - Probe_Log - INFO - Bouncing interface wlan0 (platform type = wlanpi)
2020-03-10 13:36:01,326 - Probe_Log - ERROR - if bounce command appears to have failed. Error: ifdown: interface wlan0 not configured
wpa_supplicant: /sbin/wpa_supplicant daemon failed to start
run-parts: /etc/network/if-pre-up.d/wpasupplicant exited with return code 1
ifup: failed to bring up wlan0

2020-03-10 13:36:01,327 - Probe_Log - ERROR - Returning error...
2020-03-10 13:36:01,328 - Probe_Log - ERROR - Bounce completed. Exiting script.
2020-03-10 13:36:01,329 - Probe_Log - INFO - removing lock file

**Comment by wifinigel** [comment] 2020-03-11 04:44
There is a fundamental connectivity issue here of some type at layer 3 by the looks of things. The wireless connection looks like it comes up OK and you get an IP address. The failure seems to be around the initial DNS lookup to check for Internet connectivity. The DNS lookup is a lookup to "bbc.co.uk". Is there a reason why that lookup may fail? Do you have a client you can connect to the same network  and manually test that you can test that it can get to bbc.co.uk (e.g. ping bbc.co.uk)? Are there any restrictions that may prevent the connectivity to this site in the environment that you are working in? I guess it could be a poor assumption on my part that devices will always be able to connect to the Internet and get to this site.

**Comment by wifinigel** [comment] 2020-03-11 07:14
Couple of other things to check:

1. If the hostname of the WLAN Pi has been changed from the default, make sure both /etc/hostname AND /etc/hosts are updated as per: https://wlan-pi.github.io/wlanpi-documentation/faq/#how-do-i-change-the-hostname-of-my-wlan-pi
2. Have a look at /etc/resolv.conf to make sure the correct DNS server is top of the list when the WLAN Pi is connected to the network

**Comment by blaberdia** [comment] 2020-03-11 17:31
Clients on the same network can reach bbc.co.uk and nslookup also resolves fine on other clients. The odd part is that the test does not always fail, sometimes it succeeds and other times it doesn't. I checked the hostname, hosts, and resolve files and all looked correct. Could this be some sort of driver issue with the wlanpi or an issue with armbian? Is there a way to change the nslookup the test uses to something local so I can try to isolate the problem?

**Comment by wifinigel** [comment] 2020-03-12 08:04
If it's a driver issue, there's not much I can do. I must admit that I've not had complaints from elsewhere about the issue and my own testing over many months has not picked up anything like this. The DNS sounds like the most likely area where there are issues. Can you SSH on to the WLAN Pi and check the content of the /etc/resolv.conf file - make sure your local DNS server is top of the list. If you want to hard code it, edit the file ```/etc/resolvconf/resolv.conf.d/head``` which contains 8.8.8.8 by default - any entry you add to this file will appear top of the list after a reboot. I'd suggest removing 8.8.8.8 completely.

**Comment by mik0git** [comment] 2020-10-25 15:27
Agrees, it sounds like an Interopability issue between STA and AP. 
Nigel : It could be interesting to systematicaly gather Wlan device kernel driver info from debugging logs. 
Some cheap USB dongle are known to be very badly implemented. 

I will add an issue about this topic.

**Comment by wifinigel** [comment] 2020-12-01 07:04
Unable to reproduce issue...no further info so closing (for now).

**Closed by wifinigel** 2020-12-01 07:04 UTC
